exceedMaxPackCount: "You have exceeded the maximum gift package creation limit, please delete some packages."
inventoryUploaded: "uploaded your inventory."
giftMenuOpen: "Opening gift menu..."
packageGiven: "Here are the items for this package."
packageName: "Gift Package"
expiration: "Expiration:"
missingPermission: "You do not have permission to claim this package."
hours: "h"
